# Codex CLI Configuration
# This configuration uses Azure OpenAI service, remember to replace your own instance name and API key.
model = "gpt-5"
model_provider = "azure"
model_reasoning_summary = "detailed"
show_raw_agent_reasoning = true
model_verbosity = "medium"
approval_policy = "on-request"
sandbox_mode = "workspace-write"
model_reasoning_effort = "high"

[features]
skills = true

[model_providers.azure]
name = "Azure"
base_url = "https://[YOUR-INSTANCE-NAME].openai.azure.com/openai/v1"
http_headers = { "api-key"= "[YOUR-API-KEY]"}
wire_api = "responses"
query_params = { api-version = "preview"}

# MCP Tools
[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp@latest"]

[mcp_servers.claude]
command = "claude"
args = ["mcp", "serve"]
