# Codex CLI Configuration
# This configuration uses Model Scope, remember to replace your own API key.
model = "ZhipuAI/GLM-4.5"
model_provider = "modelscope"
approval_policy = "on-request"
sandbox_mode = "workspace-write"

[features]
skills = true

[model_providers.modelscope]
name = "modelscope"
wire_api = "chat"
base_url = "https://api-inference.modelscope.cn/v1"
http_headers = { "Authorization"= "Bearer [YOUR-API-KEY]" }

# MCP Tools
[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp@latest"]

[mcp_servers.claude]
command = "claude"
args = ["mcp", "serve"]
